### PR TITLE
Website updates

### PR DESCRIPTION
**Pull request by dharabor**
Hi, 

I thought to clean up and improve and the website a bit, now that we've announced the CFP. I was going to push to a `dev`  branch but I have no access to the repo, hence this PR. 

There are 4 main changes:

1. I updated the website to en-AU (Australian/GB English). That means page content has changed spelling in a few places, and some locations (notably the "organization" content directory) has been renamed. Miguel and I have already adopted the en-AU standard and I would like to see it applied uniformly across our website. I think it's important for the website to share the cultural identity of the conference it was built for. I've yet to figure out how to change the date format though.

2. I simplified and edited the "Home" page. It now contains only descriptions of the conference scope and co-locations. All the other stuff (the "blog" style post updates) have moved to their own section. The homepage (only) also has a "News" sidebar, so visitors can easily track what's been announced. 

3. I added a "News" section and menu item (+ corresponding layout) and I updated the existing announcement posts to use this new layout. One minor bug is that the heading of the "News" section page (accessed by clicking from the menu-bar) is slightly smaller than the heading of some other pages (e.g., "Dates"). I've yet to find where to change this.

4. I updated the style used for the banner. The text was hard to read, so the container now has a background colour with 50% opacity. The text color is also updated, to an off-white rather than pure-white (seems a bit easier on the eyes). One small bug (already existing, but still notable) is that the white ICAPS logo is slightly smaller than the Title and Subtitle text. I tried to fix it, but again, I've yet to find the right style to modify.

### CODE REVIEW

**Comment by dharabor** [comment]
@miquelramirez @ssardina @nirlipo 

Not sure who is the right person to tag for this one. Comments appreciated.

**Comment by miquelramirez** [comment]
Can take a look in a tic

**Review by miquelramirez — APPROVED** [review]
Looks good

**Comment by dharabor** [comment]
I made a few more small fixes. Probably these will be merged, but please check anyway. There was one issue in particular, related to date parsing, that meant hugo could not serve the page (but the code worked when applied to a running server??) anyway!

**Comment by miquelramirez** [comment]
I am checking the PR atm on my laptop. Cheers for the heads up - as long as I don't merge before you're finished it should be okay.

**Comment by miquelramirez** [comment]
There seems to be an issue. When I host locally the website all I get is blank page ?

**Comment by miquelramirez** [comment]
Okay, I can confirm there is an issue with the changes in the PR. The `main` branch is processed by the server without problems. But when I serve after checking out the PR branch all I get is a blank page. The internet thinks that the most common cause for hugo generating blank pages is that the theme is misconfigured (or there is a problem with it). I just checked your changes under `theme/mainroad` and it all looks inocuous to me :(

**Comment by ssardina** [comment]
> I was going to push to a dev branch but I have no access to the repo, hence this PR.

mm you should have permissions to write on the repo; you and @miquelramirez for sure have done updates to it right?

I can see this PR but are you saying you cannot merge or that the merge gives error?

I am OK with all your changes @dharabor , all good ones!  :clap:

**Comment by miquelramirez** [comment]
Hi @dharabor, there is a problem with the edits you made to the `html` snippets under `/themes/mainroad/layouts`. You cannot have any text (including line breaks) outside of the template blocks. Check out the docs

https://gohugo.io/templates/base/#override-the-base-template

in `index.html` you have commented the whole thing with `<!-- ... -->` and that breaks the site.

Please remove all blanks after the ``{{main}} {{end}}`` bits and check what's going on with `index.html`.

**Comment by ssardina** [comment]
@dharabor , btw I think your GH username is not well configured in your laptop:

image

This may be the reason: https://docs.github.com/en/pull-requests/committing-changes-to-your-project/troubleshooting-commits/why-are-my-commits-linked-to-the-wrong-user

**Comment by miquelramirez** [comment]
I found it @ssardina it were the edits on the HTML snippets, hugo is a bit special with that

https://gohugo.io/templates/base/#override-the-base-template

**Comment by ssardina** [comment]
@miquelramirez , I am not understanding the problem. I pull the PR locally and run Hugo locally and it renders well, and I can see @dharabor changes:

image


What is the problem?

Yes Hugo is VERY sensitive...

**Comment by miquelramirez** [comment]
Fixed already and merged

**Pull request merged**
